version: '3'
services:
  db:
    container_name: db
    image: postgres
    ports:
    - "5432:5432"
    environment:
    -  POSTGRES_USER=postgres
    -  POSTGRES_PASSWORD=4CxphzeeFf2RAWXZ7Fu43pHTpEsZvGHEZTvqUF4p3SZuXY8kk8vU
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    - /data/postgresql:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
    - db
    environment:
      PGADMIN_DEFAULT_EMAIL: zobis2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Aa123456
    ports:
    - 8080:80
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.0.0-beta.1
    ports:
    - '2323:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_CORS_DOMAIN: *
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:4CxphzeeFf2RAWXZ7Fu43pHTpEsZvGHEZTvqUF4p3SZuXY8kk8vU@db:5432/styleclueless_back_end_production
    #          HASURA_GRAPHQL_ACCESS_KEY: lior123456
    #          HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "MCk9nkfH7JLLc4q8x2rTK7C5E9Zv4prj"}'
    command:
    - graphql-engine
    - serve
    - --enable-console
  nginx:
    restart: always
    ports:
      - "443:443"
      - "80:80"
    image: nginx:latest
    container_name: nginx
    volumes:
    - ./nginx/:/etc/nginx/
    depends_on:
    - backend
  backend:
    volumes:
    - /temp/:/temp/
    - /home/ubuntu/styleclueless/client/:/usr/src/client/
    entrypoint: node index.js
    container_name: backend
    restart: always
    build:
      context: ../
    image: styleclueless.backend:dev
#  frontend:
#      container_name: frontend
#      build:
#        context: ../../client
#        dockerfile: Dockerfile
#      image: styleclueless.frontend:dev
#      ports:
#      - "3000:3000"
#      volumes:
#      - ../../client:/usr/src/app
#AWS_ACCES_KEY  AKIAQPMQ2HDZUU4W7HQS
#AWS_SECRET_KEY  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
#AWS_HOSTED_ZONE_INSTANCE_ID Z2YG7FHHC4M32Q
